name: integration
on: 
  pull_request: 
    branches: [ main, develop ]
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Build react
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
      - run: npm run lint
      - run: npm run build
